channels:
- conda-forge
dependencies:
- python=3.11
- pyiron_base=0.10.5
- qe=7.2
- qe-tools=2.0.0
- ase=3.23.0
- matplotlib=3.8.4
- xmlschema=3.3.1
- jobflow=0.1.18
- pymatgen=2024.3.1
- aiida-core=2.6.1
- aiida-core.services
